export const transactionData = [
  {
    id: 1,
    iconClass: "i-material-symbols-download-rounded",
    title: "Title 1",
    description: "Description for Item 1",
    rightText: 154000,
    href: "#",
  },
  {
    id: 2,
    iconClass: "i-material-symbols-download-rounded",
    title: "Title 2",
    description: "Description for Item 2",
    rightText: -154000,
    href: "#",
  },
  {
    id: 3,
    iconClass: "i-material-symbols-download-rounded",
    title: "Title 3",
    description: "Description for Item 3",
    rightText: 0,
    href: "#",
  },
  {
    id: 3,
    iconClass: "i-material-symbols-download-rounded",
    title: "Title 4",
    description: "Description for Item 4",
    rightText: 154000,
    href: "#",
  },
  {
    id: 3,
    iconClass: "i-material-symbols-download-rounded",
    title: "Title 5",
    description: "Description for Item 5",
    rightText: 154000,
    href: "#",
  },
  {
    id: 3,
    iconClass: "i-material-symbols-download-rounded",
    title: "Title 6",
    description: "Description for Item 6",
    rightText: 154000,
    href: "#",
  },
  {
    id: 3,
    iconClass: "i-material-symbols-download-rounded",
    title: "Title 7",
    description: "Description for Item 7",
    rightText: -154000,
    href: "#",
  },
];
