export const transactionData = [
  {
    id: 1,
    iconClass: "i-material-symbols-download-rounded",
    title: "Mr. Archie Botsford",
    description: "20 Juni 2024",
    rightText: 154000,
    href: "#",
  },
  {
    id: 2,
    iconClass: "i-material-symbols-download-rounded",
    title: "Oliver Kihn",
    description: "20 Juni 2024",
    rightText: -154000,
    href: "#",
  },
  {
    id: 3,
    iconClass: "i-material-symbols-download-rounded",
    title: "Nichole Kunze",
    description: "20 Juni 2024",
    rightText: 0,
    href: "#",
  },
  {
    id: 4,
    iconClass: "i-material-symbols-download-rounded",
    title: "Ayrton Senna",
    description: "20 Juni 2024",
    rightText: 154000,
    href: "#",
  },
  {
    id: 5,
    iconClass: "i-material-symbols-download-rounded",
    title: "Niki Lauda",
    description: "20 Juni 2024",
    rightText: 154000,
    href: "#",
  },
  {
    id: 6,
    iconClass: "i-material-symbols-download-rounded",
    title: "Mike Tyson",
    description: "20 Juni 2024",
    rightText: 154000,
    href: "#",
  },
  {
    id: 7,
    iconClass: "i-material-symbols-download-rounded",
    title: "Steven Harvey",
    description: "20 Juni 2024",
    rightText: -154000,
    href: "#",
  },
];

export const userData = {
  id: 1,
  avatar: "https://avatar.iran.liara.run/public/28",
  name: "John Doe",
  balance: 56094343,
};
